name: "Tests"

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [master]
    tags: ["**"]

jobs:
  unit-tests:
    name: "Unit Tests for PHP ${{ matrix.php-version }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['5.6', '7.3', '7.4']
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Set up PHP ${{ matrix.php-version }}"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          extensions: mbstring, xml, ctype, iconv
          coverage: none
          tools: "composer:v2"

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('composer.*') }}
          restore-keys: |
            composer-${{ runner.os }}-${{ matrix.php-version }}-
            composer-${{ runner.os }}-
            composer-

      - name: "Install dependencies"
        run: composer install

      - name: "Run tests"
        run: php vendor/bin/phpunit
